---

# Specify your provisioning steps here.

# - name: Preliminary task
#   task: ...


# Delegate further configuration to subtasks
# placed in this same directory.

- include: prerequisites.yml
# - include: install.yml
# - include: configure.yml
# - include: contrib.yml